# The site title
title = "calcite"

# The site description
description = "an open-source multipurpose discord bot that brings cool features to your server. currently in active development."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The site URL
base_url = "https://4t88.github.io/calcite.cc"

# Enable syntax highlighting through markdown settings
[markdown]
# Enable smart quotes
smart_punctuation = true
# Enable syntax highlighting
highlight_code = true

# Enable automatic taxonomies
taxonomies = [
    {name = "tags", feed = true},
]

[extra]
# Put any custom variables here
github_url = "https://github.com/4T88/calcite"
website_github_url = "https://github.com/4T88/calcite.cc"
discord_invite = "https://discord.gg/a7Z6XRFVbJ"